openapi: 3.0.3
info:
  title: "二手优选小程序 API V1.2"
  description: "这是一个为“二手优选”微信小程序设计的后端API文档，涵盖了用户、商品、订单、消息等核心模块。V1.2版本对所有请求和响应进行了Schema封装（Request/VO后缀），并根据小程序支付流程优化了订单接口，结构更清晰，对接更友好。"
  version: "1.2.3"
servers:
  - url: https://api.example.com/v1
    description: 生产环境服务器

tags:
  - name: Auth
    description: 用户认证
  - name: Products
    description: 商品相关操作
  - name: Categories
    description: 商品分类
  - name: Users
    description: 用户个人中心相关操作
  - name: Orders
    description: 订单管理与支付
  - name: Notifications
    description: 消息中心
  - name: Files
    description: 文件上传服务

paths:
  # ======================================================
  # Auth - 认证模块
  # ======================================================
  /auth/login:
    post:
      tags:
        - Auth
      summary: "微信小程序登录"
      description: "前端调用wx.login()获取code，发送给后端换取自定义登录态（JWT Token）。"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/LoginRequest'
      responses:
        "200":
          description: "登录成功"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/LoginResponseVO'

  # ======================================================
  # Products - 商品模块
  # ======================================================
  /products:
    get:
      tags:
        - Products
      summary: "获取商品列表（首页/搜索/我的发布）"
      description: "通用商品列表接口。可通过关键词、分类、卖家ID进行筛选和分页。"
      parameters:
        - name: query
          in: query
          description: "搜索关键词"
          schema:
            type: string
        - name: categoryId
          in: query
          description: "分类ID"
          schema:
            type: string
        - name: sellerId
          in: query
          description: "卖家ID。传入 'me' 可查询当前登录用户的商品。"
          schema:
            type: string
        - name: page
          in: query
          description: "页码，从1开始"
          schema:
            type: integer
            default: 1
        - name: size
          in: query
          description: "每页数量"
          schema:
            type: integer
            default: 10
      responses:
        "200":
          description: "成功返回商品分页列表"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProductListVO'
    post:
      tags:
        - Products
      summary: "发布新商品"
      security:
        - BearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateProductRequest'
      responses:
        "201":
          description: "商品创建成功"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProductDetailVO'
        "400":
          description: "请求参数错误"

  /products/{id}:
    get:
      tags:
        - Products
      summary: "获取商品详情"
      parameters:
        - name: id
          in: path
          required: true
          description: "商品ID"
          schema:
            type: string
      responses:
        "200":
          description: "成功返回商品详情"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProductDetailVO'
        "404":
          description: "商品未找到"

  # ======================================================
  # Categories - 分类模块
  # ======================================================
  /categories:
    get:
      tags:
        - Categories
      summary: "获取所有商品分类"
      responses:
        "200":
          description: "成功返回分类列表"
          content:
            application/json:
              schema:
                type: object
                properties:
                  items:
                    type: array
                    items:
                      $ref: '#/components/schemas/CategoryVO'

  # ======================================================
  # Users - 用户模块
  # ======================================================
  /users/me:
    get:
      tags:
        - Users
      summary: "获取当前用户信息"
      security:
        - BearerAuth: []
      responses:
        "200":
          description: "成功"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserProfileVO'
    patch:
      tags:
        - Users
      summary: "更新当前用户信息"
      security:
        - BearerAuth: []
      requestBody:
        description: "需要更新的用户字段"
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateUserRequest'
      responses:
        "200":
          description: "更新成功"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserProfileVO'
        "400":
          description: "请求数据无效"

  /users/me/favorites:
    get:
      tags:
        - Users
      summary: "获取我的收藏列表"
      security:
        - BearerAuth: []
      parameters:
        - name: page
          in: query
          description: "页码，从1开始"
          schema:
            type: integer
            default: 1
        - name: size
          in: query
          description: "每页数量"
          schema:
            type: integer
            default: 10
      responses:
        "200":
          description: "成功返回收藏的商品列表"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProductListVO' # 复用商品列表分页结构
    post:
      tags:
        - Users
      summary: "添加商品到收藏夹"
      security:
        - BearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AddFavoriteRequest'
      responses:
        "204":
          description: "收藏成功，无返回内容"

  /users/me/favorites/{productId}:
    delete:
      tags:
        - Users
      summary: "从收藏夹移除商品"
      security:
        - BearerAuth: []
      parameters:
        - name: productId
          in: path
          required: true
          description: "商品ID"
          schema:
            type: string
      responses:
        "204":
          description: "取消收藏成功，无返回内容"

  /users/{id}/follow:
    post:
      tags:
        - Users
      summary: "关注用户"
      security:
        - BearerAuth: []
      parameters:
        - name: id
          in: path
          required: true
          description: "被关注用户的ID"
          schema:
            type: string
      responses:
        "204":
          description: "关注成功"
    delete:
      tags:
        - Users
      summary: "取消关注用户"
      security:
        - BearerAuth: []
      parameters:
        - name: id
          in: path
          required: true
          description: "被取消关注用户的ID"
          schema:
            type: string
      responses:
        "204":
          description: "取消关注成功"

  # ======================================================
  # Orders - 订单模块
  # ======================================================
  /orders:
    get:
      tags:
        - Orders
      summary: "获取我的订单列表"
      security:
        - BearerAuth: []
      parameters:
        - name: status
          in: query
          description: "订单状态: ToPay, ToShip, ToReceive, Completed, Canceled"
          schema:
            type: string
            enum: [ToPay, ToShip, ToReceive, Completed, Canceled]
        - name: page
          in: query
          description: "页码，从1开始"
          schema:
            type: integer
            default: 1
        - name: size
          in: query
          description: "每页数量"
          schema:
            type: integer
            default: 10
      responses:
        "200":
          description: "成功返回订单分页列表"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/OrderListVO'
    post:
      tags:
        - Orders
      summary: "创建订单并获取微信支付参数"
      description: "此接口用于“立即购买”。后端在创建内部订单后，会向微信支付服务器请求预支付交易，并将返回的支付参数直接透传给小程序，小程序前端接收后调用wx.requestPayment()拉起支付。支付结果通过微信的异步通知更新。"
      security:
        - BearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateOrderRequest'
      responses:
        "201":
          description: "订单创建成功，返回支付所需参数"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/WeChatPayParamsVO'
        "400":
          description: "请求参数错误或商品库存不足"

  # ======================================================
  # Notifications - 消息模块
  # ======================================================
  /notifications:
    get:
      tags:
        - Notifications
      summary: "获取消息列表"
      security:
        - BearerAuth: []
      parameters:
        - name: type
          in: query
          description: "消息类型: system, transaction"
          schema:
            type: string
            enum: [system, transaction]
        - name: page
          in: query
          description: "页码，从1开始"
          schema:
            type: integer
            default: 1
        - name: size
          in: query
          description: "每页数量"
          schema:
            type: integer
            default: 10
      responses:
        "200":
          description: "成功返回消息分页列表"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/NotificationListVO'

  # ======================================================
  # Files - 文件上传模块
  # ======================================================
  /files/upload:
    post:
      tags:
        - Files
      summary: "上传多个文件（如商品图片、用户头像）" #<-- [修改] 摘要更新为“多个文件”
      security:
        - BearerAuth: []
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                files: # <-- [关键修改 1] key 从 'file' 改为 'files' 以匹配后端代码
                  type: array # <-- [关键修改 2] 类型改为数组 array
                  items:
                    type: string
                    format: binary
                  description: "要上传的文件列表。在Swagger UI或Postman中，您可以多次选择此字段来添加多个文件。"
      responses:
        "200":
          description: "所有文件上传成功"
          content:
            application/json:
              schema: # <-- [关键修改 3] 直接定义响应体结构
                $ref: '#/components/schemas/FileUploadResponseVO'

# ======================================================
# Reusable Components - 可复用组件
# ======================================================
components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
      description: "在请求的Authorization头中添加'Bearer '前缀和Token，例如: 'Bearer ey...'"

  schemas:
    # -------------------
    # Request Schemas
    # -------------------
    LoginRequest:
      type: object
      required: [code]
      properties:
        code:
          type: string
          description: "微信登录凭证 wx.login() 获取的 code"
          example: "0a3j4H1..."

    CreateProductRequest:
      type: object
      required: [title, description, price, stock, categoryId, imageUrls]
      properties:
        title:
          type: string
          example: "九成新山地自行车"
        description:
          type: string
          example: "详细描述一下你的宝贝吧..."
        price:
          type: number
          format: float
        stock:
          type: integer
          default: 1
        categoryId:
          type: string
          example: "cat_digital"
        imageUrls:
          type: array
          minItems: 1
          items:
            type: string
            format: uri

    UpdateUserRequest:
      type: object
      properties:
        nickname:
          type: string
          description: "新昵称 (可选)"
        avatarUrl:
          type: string
          format: uri
          description: "新头像URL (可选, 前端需先调用文件上传接口)"

    AddFavoriteRequest:
      type: object
      required: [productId]
      properties:
        productId:
          type: string
          description: "要收藏的商品ID"

    CreateOrderRequest:
      type: object
      required: [productId, quantity]
      properties:
        productId:
          type: string
        quantity:
          type: integer
          default: 1

    # -------------------
    # View Object (VO) Schemas
    # -------------------
    LoginResponseVO:
      type: object
      properties:
        token:
          type: string
          description: "JWT Token，后续请求需在Header中携带"
          example: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9..."
        user:
          $ref: '#/components/schemas/UserProfileVO'

    FileUploadResponseVO:
      type: object
      properties:
        urls:
          type: array
          items:
            type: string
            format: uri
          description: "文件的可访问URL"
          example: [ "https://cdn.example.com/images/12345.jpg" ]

    WeChatPayParamsVO:
      type: object
      description: "调用wx.requestPayment所需的支付参数"
      properties:
        appId:
          type: string
        timeStamp:
          type: string
          description: "时间戳，从1970年1月1日00:00:00至今的秒数"
        nonceStr:
          type: string
          description: "随机字符串，不长于32位"
        package:
          type: string
          description: "统一下单接口返回的 prepay_id 参数值，格式：prepay_id=xxx"
        signType:
          type: string
          description: "签名类型，默认为RSA"
          example: "RSA"
        paySign:
          type: string
          description: "签名"
        orderId:
          type: string
          description: "本次支付关联的系统内部订单ID，可用于支付成功后的页面跳转"


    UserProfileVO:
      type: object
      properties:
        userId:
          type: string
          example: "user_12345678"
        nickname:
          type: string
          example: "Emily Chen"
        avatarUrl:
          type: string
          format: uri
        joinDate:
          type: string
          format: date
          example: "2021-01-01"

    ProductSummaryVO:
      type: object
      properties:
        productId:
          type: string
          example: "prod_123"
        title:
          type: string
          example: "全新时尚连衣裙"
        mainImageUrl:
          type: string
          format: uri
          example: "https://example.com/dress.jpg"
        price:
          type: number
          format: float
          example: 85.00

    ProductDetailVO:
      type: object
      properties:
        productId:
          type: string
          example: "prod_456"
        title:
          type: string
          example: "复古牛仔夹克"
        description:
          type: string
          example: "经典牛仔夹克，状况良好。M 码。非常适合叠穿。"
        price:
          type: number
          format: float
          example: 150.00
        imageUrls:
          type: array
          items:
            type: string
            format: uri
        stock:
          type: integer
          example: 1
        sellerInfo:
          $ref: '#/components/schemas/UserProfileVO'
        isFavorite:
          type: boolean
          description: "当前用户是否已收藏该商品"
          example: false
        isFollowingSeller:
          type: boolean
          description: "当前用户是否已关注该卖家"
          example: true
        postedAt:
          type: string
          format: date-time
        reviews:
          type: array
          items:
            $ref: '#/components/schemas/ReviewVO'

    CategoryVO:
      type: object
      properties:
        categoryId:
          type: string
          example: "cat_fashion"
        name:
          type: string
          example: "时尚服饰"
        iconUrl:
          type: string
          format: uri

    OrderSummaryVO:
      type: object
      description: "订单摘要信息。由于业务规则为一次只购买一件商品，该结构已扁平化，直接包含商品信息。"
      properties:
        orderId:
          type: string
          description: "系统内部的订单ID"
          example: "order_789"
        status:
          type: string
          description: "订单状态"
          example: "ToShip"
        totalPrice:
          type: number
          format: float
          description: "订单总金额，等于 priceAtPurchase * quantity"
          example: 150.00
        productId:
          type: string
          description: "所购买的商品ID"
          example: "prod_456"
        productTitle:
          type: string
          description: "所购买的商品标题"
          example: "复古牛仔夹克"
        productMainImageUrl:
          type: string
          format: uri
          description: "所购买的商品主图"
        priceAtPurchase:
          type: number
          format: float
          description: "下单时商品的单价快照"
          example: 150.00
        quantity:
          type: integer
          description: "购买数量"
          example: 1

    ReviewVO:
      type: object
      properties:
        reviewId:
          type: string
        author:
          $ref: '#/components/schemas/UserProfileVO'
        content:
          type: string
          example: "很棒的夹克！和描述的一模一样。"
        createdAt:
          type: string
          format: date-time

    NotificationVO:
      type: object
      properties:
        notificationId:
          type: string
        type:
          type: string
          enum: [system, transaction]
          example: "system"
        title:
          type: string
          example: "您的商品已被下架"
        content:
          type: string
          example: "由于违反社区规定，您的商品'违规商品名称'已被下架处理。"
        createdAt:
          type: string
          format: date-time
        isRead:
          type: boolean
          example: false

    # -------------------
    # List Wrapper VOs
    # -------------------
    ProductListVO:
      type: object
      properties:
        items:
          type: array
          items:
            $ref: '#/components/schemas/ProductSummaryVO'
        totalPages:
          type: integer
        totalElements:
          type: integer

    OrderListVO:
      type: object
      properties:
        items:
          type: array
          items:
            $ref: '#/components/schemas/OrderSummaryVO'
        totalPages:
          type: integer
        totalElements:
          type: integer

    NotificationListVO:
      type: object
      properties:
        items:
          type: array
          items:
            $ref: '#/components/schemas/NotificationVO'
        totalPages:
          type: integer
        totalElements:
          type: integer